/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "SSH": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "TodoPlannerKey": {
      "private": string
      "public": string
      "type": "tls.index/privateKey.PrivateKey"
    }
    "TodoPlannerVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "TodoPlannner": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}